project_id = "tnalryxoxswjofmtdtaf"

[functions.area-analysis]
verify_jwt = false

[functions.property-assessment]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.fetch-stats]
verify_jwt = true

[functions.installation-detail]
verify_jwt = false

[functions.import-solar-data]
verify_jwt = true

[functions.sync-solar-data]
verify_jwt = false

[functions.check-api-fields]
verify_jwt = false

[functions.yearly-stats]
verify_jwt = false

[functions.fiscal-year-stats]
verify_jwt = false

[functions.permit-timeline-stats]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.manage-corrections]
verify_jwt = false
